use_frameworks!

platform :ios, '10.0'

target 'SocketIOKotlinIOS_Example' do
  pod 'SocketIOKotlinIOS', :path => '../'

  target 'SocketIOKotlinIOS_Tests' do
    inherit! :search_paths

    pod 'Socket.IO-Client-Swift', '~> 16.0'
  end
end
