use_frameworks!

platform :ios, '10.0'

target 'SocketIOKotlinIOS_Example' do
  pod 'SocketIOKotlinIOS', :path => '../'

  target 'SocketIOKotlinIOS_Tests' do
    inherit! :search_paths

    
  end
end
